### ISSUE TITLE
Not working under windows

### ISSUE THREAD

**Issue by Enzojz** [adrien-ben/rtx-on-rs#1]
Hi I am trying to run it under windows however the script of shader compilation is written in sh, so it can't be used under windows, would you like to write a bat version?

**Comment by adrien-ben** [comment]
Hi ! 

I just added a Powershell version of the sh shader compilation script https://github.com/adrien-ben/rtx-on-rs/commit/686c696d073713484c5a88aa0e504a0022a51ad6

Let me know if it works for you :)
